// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/mocks/service_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:frontend/core/session/services/auth_service.dart' as _i4;
import 'package:frontend/features/claims/data/claims_service.dart' as _i9;
import 'package:frontend/features/items/data/items_service.dart' as _i6;
import 'package:frontend/features/items/data/models/item_model.dart' as _i2;
import 'package:frontend/features/reports/data/models/report_model.dart' as _i3;
import 'package:frontend/features/reports/data/services/report_service.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeItemModel_0 extends _i1.SmartFake implements _i2.ItemModel {
  _FakeItemModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReport_1 extends _i1.SmartFake implements _i3.Report {
  _FakeReport_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  _i5.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> register(
    String? fullName,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            fullName,
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [ItemsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsService extends _i1.Mock implements _i6.ItemsService {
  @override
  _i5.Future<String> uploadImage({
    String? filePath,
    _i7.Uint8List? bytes,
    String? fileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [],
          {
            #filePath: filePath,
            #bytes: bytes,
            #fileName: fileName,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {
              #filePath: filePath,
              #bytes: bytes,
              #fileName: fileName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {
              #filePath: filePath,
              #bytes: bytes,
              #fileName: fileName,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i2.ItemModel>> getItems({
    bool? forceRefresh = false,
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItems,
          [],
          {
            #forceRefresh: forceRefresh,
            #ttl: ttl,
          },
        ),
        returnValue: _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
      ) as _i5.Future<List<_i2.ItemModel>>);

  @override
  _i5.Future<List<_i2.ItemModel>> getMyPostedItems() => (super.noSuchMethod(
        Invocation.method(
          #getMyPostedItems,
          [],
        ),
        returnValue: _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
      ) as _i5.Future<List<_i2.ItemModel>>);

  @override
  _i5.Future<List<_i2.ItemModel>> getAdminItems({
    bool? forceRefresh = false,
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdminItems,
          [],
          {
            #forceRefresh: forceRefresh,
            #ttl: ttl,
          },
        ),
        returnValue: _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
      ) as _i5.Future<List<_i2.ItemModel>>);

  @override
  _i5.Future<_i2.ItemModel?> getItemById(
    String? id, {
    bool? forceRefresh = false,
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemById,
          [id],
          {
            #forceRefresh: forceRefresh,
            #ttl: ttl,
          },
        ),
        returnValue: _i5.Future<_i2.ItemModel?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.ItemModel?>.value(),
      ) as _i5.Future<_i2.ItemModel?>);

  @override
  _i5.Future<_i2.ItemModel> createItem({
    required String? title,
    required String? location,
    required String? description,
    required String? verificationQuestion,
    required String? verificationAnswer,
    String? category = 'Other',
    String? imageUrl,
    String? imagePath,
    _i7.Uint8List? imageBytes,
    String? imageFileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createItem,
          [],
          {
            #title: title,
            #location: location,
            #description: description,
            #verificationQuestion: verificationQuestion,
            #verificationAnswer: verificationAnswer,
            #category: category,
            #imageUrl: imageUrl,
            #imagePath: imagePath,
            #imageBytes: imageBytes,
            #imageFileName: imageFileName,
          },
        ),
        returnValue: _i5.Future<_i2.ItemModel>.value(_FakeItemModel_0(
          this,
          Invocation.method(
            #createItem,
            [],
            {
              #title: title,
              #location: location,
              #description: description,
              #verificationQuestion: verificationQuestion,
              #verificationAnswer: verificationAnswer,
              #category: category,
              #imageUrl: imageUrl,
              #imagePath: imagePath,
              #imageBytes: imageBytes,
              #imageFileName: imageFileName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ItemModel>.value(_FakeItemModel_0(
          this,
          Invocation.method(
            #createItem,
            [],
            {
              #title: title,
              #location: location,
              #description: description,
              #verificationQuestion: verificationQuestion,
              #verificationAnswer: verificationAnswer,
              #category: category,
              #imageUrl: imageUrl,
              #imagePath: imagePath,
              #imageBytes: imageBytes,
              #imageFileName: imageFileName,
            },
          ),
        )),
      ) as _i5.Future<_i2.ItemModel>);

  @override
  _i5.Future<bool> updateItem({
    required String? id,
    required String? title,
    required String? location,
    String? description,
    String? category,
    String? verificationQuestion,
    String? verificationAnswer,
    String? status,
    String? imageUrl,
    String? imagePath,
    _i7.Uint8List? imageBytes,
    String? imageFileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [],
          {
            #id: id,
            #title: title,
            #location: location,
            #description: description,
            #category: category,
            #verificationQuestion: verificationQuestion,
            #verificationAnswer: verificationAnswer,
            #status: status,
            #imageUrl: imageUrl,
            #imagePath: imagePath,
            #imageBytes: imageBytes,
            #imageFileName: imageFileName,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> submitClaim({
    required String? itemId,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitClaim,
          [],
          {
            #itemId: itemId,
            #answer: answer,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> invalidateItemCache({String? id}) => (super.noSuchMethod(
        Invocation.method(
          #invalidateItemCache,
          [],
          {#id: id},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> invalidateClaimsCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidateClaimsCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ClaimsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClaimsService extends _i1.Mock implements _i9.ClaimsService {
  @override
  _i5.Future<List<dynamic>> getClaims({
    bool? forceRefresh = false,
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClaims,
          [],
          {
            #forceRefresh: forceRefresh,
            #ttl: ttl,
          },
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getClaimById(
    String? id, {
    bool? forceRefresh = false,
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClaimById,
          [id],
          {
            #forceRefresh: forceRefresh,
            #ttl: ttl,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> invalidateClaimsCache({String? id}) => (super.noSuchMethod(
        Invocation.method(
          #invalidateClaimsCache,
          [],
          {#id: id},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> withdrawClaim(String? id) => (super.noSuchMethod(
        Invocation.method(
          #withdrawClaim,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteClaim(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteClaim,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [ReportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportService extends _i1.Mock implements _i10.ReportService {
  @override
  _i5.Future<Map<String, dynamic>> createReport({
    required int? itemId,
    required int? claimId,
    required String? reason,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReport,
          [],
          {
            #itemId: itemId,
            #claimId: claimId,
            #reason: reason,
            #description: description,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i3.Report>> getMyReports() => (super.noSuchMethod(
        Invocation.method(
          #getMyReports,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Report>>.value(<_i3.Report>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.Report>>.value(<_i3.Report>[]),
      ) as _i5.Future<List<_i3.Report>>);

  @override
  _i5.Future<List<_i3.Report>> getAllReports() => (super.noSuchMethod(
        Invocation.method(
          #getAllReports,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Report>>.value(<_i3.Report>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.Report>>.value(<_i3.Report>[]),
      ) as _i5.Future<List<_i3.Report>>);

  @override
  _i5.Future<_i3.Report> getReportById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getReportById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Report>.value(_FakeReport_1(
          this,
          Invocation.method(
            #getReportById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Report>.value(_FakeReport_1(
          this,
          Invocation.method(
            #getReportById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Report>);

  @override
  _i5.Future<void> updateReportStatus(
    String? id,
    String? status, {
    String? adminNote,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReportStatus,
          [
            id,
            status,
          ],
          {#adminNote: adminNote},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteReport(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReport,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
